- hosts: localhost
  vars:
    ssh_folder: "./.ssh"
    dest_ssh_folder: "{{ lookup('env', 'HOME') }}/.ssh"
    code: "{{ lookup('env', 'HOME') }}/code"
    personal: "{{ code }}/personal"
    work: "{{ code }}/work"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/node.yml
    - include: tasks/npm.yml
    - include: tasks/core.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/golang.yml
    - include: tasks/python.yml
    - include: tasks/python-packages.yml
    - include: tasks/personal-projects.yml
    - include: tasks/nvim.yml
    - include: tasks/postgres.yml
    - include: tasks/redis.yml
    - include: tasks/programs.yml
    - include: tasks/brave.yml
