- name: Install Sys Packages 1.0 (curl, fzf, gettext, ripgrep)
  become: true
  apt:
    name: ["curl", "fzf", "gettext", "ripgrep"]
  tags:
    - install
    - core
- name: Install Sys Programs 1.0 (i3, tmux)
  become: true
  apt:
    name: ["i3", "tmux"]
  tags:
    - install
    - core
