# Dart
# - name: Install Dart
#   become: true
#   snap:
#     name: dart
#   tags:
#     - dart
#     - install
# Dart
# - name: Install Public key for Repo
#   become: true
#   shell: wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
#   tags:
#     - install
#     - dart
# - name: Install Dart
#   become: true
#   apt:
#     name: dart 
#   tags:
#     - install
#     - dart
# Flutter
# - name: Install Postman
#   become: true
#   snap:
#     name: flutter
#   tags:
#     - install
#     - flutter
