- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
    - install
- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - docker
    - install
- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: latest
  tags:
    - docker
    - install
