- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_ssh_folder }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
# ssh keys for tpotjj --> Github
- name: Install tpotjj ssh key
  copy:
    src: "{{ ssh_folder }}/id_rsa_tpotjj"
    dest: "{{ dest_ssh_folder }}/id_rsa_tpotjj"
    mode: 0600
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
- name: Install tpotjj ssh key public
  copy:
    src: "{{ ssh_folder }}/id_rsa_tpotjj.pub"
    dest: "{{ dest_ssh_folder }}/id_rsa_tpotjj.pub"
    mode: 0644
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
# ssh keys for Joris2Jansen --> Github
- name: Install Joris2Jansen ssh key
  copy:
    src: "{{ ssh_folder }}/id_rsa_Joris2Jansen"
    dest: "{{ dest_ssh_folder }}/id_rsa_Joris2Jansen"
    mode: 0600
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
- name: Install Joris2Jansen ssh key public
  copy:
    src: "{{ ssh_folder }}/id_rsa_Joris2Jansen.pub"
    dest: "{{ dest_ssh_folder }}/id_rsa_Joris2Jansen.pub"
    mode: 0644
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
# ssh keys for joris-jansen --> Bitbucket
- name: Install joris-jansen ssh key
  copy:
    src: "{{ ssh_folder }}/id_rsa_joris-jansen"
    dest: "{{ dest_ssh_folder }}/id_rsa_joris-jansen"
    mode: 0600
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
- name: Install joris-jansen ssh key public
  copy:
    src: "{{ ssh_folder }}/id_rsa_joris-jansen"
    dest: "{{ dest_ssh_folder }}/id_rsa_joris-jansen.pub"
    mode: 0644
  tags:
    - install
    - ssh
    - personal-projects
    - dotfiles
